### ISSUE TITLE
Support browserlist

### ISSUE THREAD

**Issue by the-ult** [mrmlnc/vscode-doiuse#44]
Just installed the extention and  it works great.
Would be really nice if the setting:
`"doiuse.browsers"`
would default to the local `browserlist` file: https://github.com/ai/browserslist

**Comment by mrmlnc** [comment]
Hello, @the-ult,

I don't fully understand what is mean. This plugin uses *doiuse* package that install *browserlist* package as dependencies.

**Comment by the-ult** [comment]
Aah.. So it might work out of the box?

[browserslist](https://github.com/ai/browserslist) can be used by postcss.
You can create a file: `browserslist` with the browserstring:
```bash
# Browsers that we support

> 1%
Last 2 versions
IE 8 # sorry
```
This can be/is used by `autoprefixer` etc

If the plugin can read this file instead of the settings from settings.json
`// An autoprefixer-like array of browsers.
  "doiuse.browsers": ["> 1%", "last 2 versions", "ie >= 10", "not OP_MINI all", "Android > 4.4"],`
That would mean you won't have to define the browserlist twice (in `browerslist` and in the settings)

**Comment by mrmlnc** [comment]
Thanks, now I understand that you talking about config file. I'll work on this functional on next week.

**Comment by the-ult** [comment]
Thanks! That would be awesome!

**Comment by mrmlnc** [comment]
Please, look at `1.4.0` version 🐼

**Comment by the-ult** [comment]
Cool! thanks! Gonna check it out 👍
